package com.breezenationalplasticfsm.app.types

/**
 * Created by rp : 30-10-2017:12:40
 */
enum class TopBarConfig {
    HOME,
    BACK, ADDSHOP, DASHBOARD, SHOPLIST, MAPVIEW, GPS, CART, ADDATTENDANCE, CARTDETAILS, LOGOUTSYNC, REIMBURSEMENT,SHOPLISTV1, VISITREPORTDETAILS,
    NOTIFICATION, SEARCHLOCATION, SEARCHLOCATIONFROMADDSHOP, TARGETPLAN, TARGETPLANBACK, TARGETPLANDETAILSBACK, TARGETPLANGPS,
    ALLSHOPLIST, ACTIVITYMAP, ORDERLIST, LOCALSHOP, MEMBERSHOPLIST, OFFLINESHOPLIST, OFFLINEMEMBERLIST, TIMESHEETLIST, ONLINEMEMBERLIST,
    ACTIVITSHOP, WEATHERMAP, TASKLIST, MEMBERACTIVITYMAP, ATTENDENCELIST, ATTENDENCEBACKLIST, LEAVELIST, CHATBOT, CHATUSER, NEWGROUP,
    CHAT, SHOPDETAILS, CHATBOTSHOP, BEATLIST, MICROLEARNING, CUSTOMER, PHOTOREG,NEWORDERSCRCART,NEWORDERCART,LEADFR,TEAMMAP,DISTWISEORDER,NONE, CONTACT , SCHEDULER , SCHEDULER_LIST,

    TEMPLATE_LIST,HOME_BACK,LEADERBOARD,LEADERBOARD_OWN,GENERAL_HOME_BACK,GENERAL_HOME_MENU,MENU_ONLY_BACK,MENU_ONLY_BACK_WITH_REFRESH,MyLearning,LMS_SEARCH,LMS_VIDEO,LEADERBOARD_LMS,LEADERBOARD_OWN_LMS,Performance_LMS,QUESTION_ANSWER_SET

}